const CategoryActionType = {
    FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',
    SET_CURRENT_CATEGORY : 'SET_CURRENT_CATEGORY'
    

}

export default CategoryActionType;