const SubCategoryActionType = {
    FETCH_SUBCATEGORY_START: 'FETCH_SUBCATEGORY_START',
    FETCH_SUBCATEGORY_SUCCESS: 'FETCH_SUBCATEGORY_SUCCESS',
    FETCH_SUBCATEGORY_FAILURE: 'FETCH_SUBCATEGORY_FAILURE',
    SET_CURRENT_SUBCATEGORY: 'SET_CURRENT_SUBCATEGORY',
    

}

export default SubCategoryActionType;