const BrandsActionType = {
    FETCH_BRANDS_START: 'FETCH_BRANDS_START',
    FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',
    FETCH_BRANDS_FAILURE: 'FETCH_BRANDS_FAILURE',
    SET_CURRENT_BRAND: 'SET_CURRENT_BRAND',

}

export default BrandsActionType;