const RolesActionType = {
    FETCH_ROLES_START: 'FETCH_ROLES_START',
    FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
    FETCH_ROLES_FAILURE: 'FETCH_ROLES_FAILURE',
    SET_CURRENT_ROLE: 'SET_CURRENT_ROLE',

}

export default RolesActionType;