const ExpenseActionType = {
    FETCH_EXPENSE_START: 'FETCH_EXPENSE_START',
    FETCH_EXPENSE_SUCCESS: 'FETCH_EXPENSE_SUCCESS',
    FETCH_EXPENSE_FAILURE: 'FETCH_EXPENSE_FAILURE',
    SET_CURRENT_EXPENSE: 'SET_CURRENT_EXPENSE',

}

export default ExpenseActionType;