const StockActionType = {
    FETCH_STOCK_START: 'FETCH_STOCK_START',
    FETCH_STOCK_SUCCESS: 'FETCH_STOCK_SUCCESS',
    FETCH_STOCK_FAILURE: 'FETCH_STOCK_FAILURE',
    SET_CURRENT_STOCK: 'SET_CURRENT_STOCK',

}

export default StockActionType;