const SiteManagementActionType = {
    FETCH_SITEMANAGEMENT_START: 'FETCH_SITEMANAGEMENT_START',
    FETCH_SITEMANAGEMENT_SUCCESS: 'FETCH_SITEMANAGEMENT_SUCCESS',
    FETCH_SITEMANAGEMENT_FAILURE: 'FETCH_SITEMANAGEMENT_FAILURE'

}

export default SiteManagementActionType;