const PurchaseActionType = {
    FETCH_PURCHASE_START: 'FETCH_PURCHASE_START',
    FETCH_PURCHASE_SUCCESS: 'FETCH_PURCHASE_SUCCESS',
    FETCH_PURCHASEINVOICEDETAIL_SUCCESS :'FETCH_PURCHASEINVOICEDETAIL_SUCCESS',
    FETCH_PURINVPAYDETIAL_SUCCESS: 'FETCH_PURINVPAYDETIAL_SUCCESS',
    FETCH_PURCHASE_FAILURE: 'FETCH_PURCHASE_FAILURE',
    SET_CURRENT_PURCHASE: 'SET_CURRENT_PURCHASE',
}

export default PurchaseActionType;