const PurchaseActionType = {
    FETCH_PURCHASE_START: 'FETCH_PURCHASE_START',
    FETCH_PURCHASE_SUCCESS: 'FETCH_PURCHASE_SUCCESS',
    FETCH_PURCHASEINVOICEDETAIL_SUCCESS :'FETCH_PURCHASEINVOICEDETAIL_SUCCESS',
    FETCH_PURCHASEAP_SUCCESS :'FETCH_PURCHASEAP_SUCCESS',
    FETCH_PURINVPAYDETIAL_SUCCESS: 'FETCH_PURINVPAYDETIAL_SUCCESS',
    FETCH_PURCHASE_FAILURE: 'FETCH_PURCHASE_FAILURE',
    SET_CURRENT_PURCHASE: 'SET_CURRENT_PURCHASE',
    FETCH_PURCHASESUMMARY_START: 'FETCH_PURCHASESUMMARY_START',
    FETCH_PURCHASESUMMARY_SUCCESS: 'FETCH_PURCHASESUMMARY_SUCCESS',
    FETCH_PURCHASESUMMARY_FAILURE: 'FETCH_PURCHASESUMMARY_FAILURE',
    FETCH_EDITPURCHASE_START: 'FETCH_EDITPURCHASE_START',
    FETCH_EDITPURCHASE_SUCCESS: 'FETCH_EDITPURCHASE_SUCCESS',
    FETCH_EDITPURCHASE_FAILURE: 'FETCH_EDITPURCHASE_FAILURE',
}

export default PurchaseActionType;