const UserActionType = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    REGISTER_SUCCESS : "REGISTER_SUCCESS",
    REGISTER_FAIL : "REGISTER_FAIL",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",
    LOGOUT : "LOGOUT",

    SET_MESSAGE : "SET_MESSAGE",
    CLEAR_MESSAGE : "CLEAR_MESSAGE",
}

export default UserActionType;

