const CashFlowActionType = {
    FETCH_CASHFLOW_START: 'FETCH_CASHFLOW_START',
    FETCH_CASHFLOW_SUCCESS: 'FETCH_CASHFLOW_SUCCESS',
    FETCH_CASHFLOW_FAILURE: 'FETCH_CASHFLOW_FAILURE',
    FETCH_CASHFLOWAR_SUCCESS :'FETCH_CASHFLOWAR_SUCCESS',
    FETCH_CASHFLOWAP_SUCCESS :'FETCH_CASHFLOWAP_SUCCESS',
    FETCH_CASHFLOWPAY_SUCCESS :'FETCH_CASHFLOWPAY_SUCCESS',
    
}

export default CashFlowActionType;