const ItemActionType = {
    FETCH_ITEM_START: 'FETCH_ITEM_START',
    FETCH_ITEM_SUCCESS: 'FETCH_ITEM_SUCCESS',
    FETCH_ITEM_FAILURE: 'FETCH_ITEM_FAILURE',
    SET_CURRENT_ITEM: 'SET_CURRENT_ITEM',
}

export default ItemActionType;