const SaleActionType = {
    FETCH_SALE_START: 'FETCH_SALE_START',
    FETCH_SALE_SUCCESS: 'FETCH_SALE_SUCCESS',
    FETCH_SALE_FAILURE: 'FETCH_SALE_FAILURE',
    FETCH_SALESUMMARY_START: 'FETCH_SALESUMMARY_START',
    FETCH_SALESUMMARY_SUCCESS: 'FETCH_SALESUMMARY_SUCCESS',
    FETCH_SALESUMMARY_FAILURE: 'FETCH_SALESUMMARY_FAILURE',
    FETCH_SALEINVOICEDETAIL_SUCCESS :'FETCH_SALEINVOICEDETAIL_SUCCESS',
    FETCH_SALEAR_SUCCESS :'FETCH_SALEAR_SUCCESS',
    FETCH_SALINVPAYDETIAL_SUCCESS: 'FETCH_SALINVPAYDETIAL_SUCCESS',
    SET_SALE_PURCHASE: 'SET_CURRENT_SALE',
    FETCH_SALEPAYHIST_START: 'FETCH_SALEPAYHIST_START',
    FETCH_SALEPAYHIST_SUCCESS: 'FETCH_SALEPAYHIST_SUCCESS',
    FETCH_SALEPAYHIST_FAILURE: 'FETCH_SALEPAYHIST_FAILURE',
}

export default SaleActionType;