const SaleActionType = {
    FETCH_SALE_START: 'FETCH_SALE_START',
    FETCH_SALE_SUCCESS: 'FETCH_SALE_SUCCESS',
    FETCH_SALEINVOICEDETAIL_SUCCESS :'FETCH_SALEINVOICEDETAIL_SUCCESS',
    FETCH_SALINVPAYDETIAL_SUCCESS: 'FETCH_SALINVPAYDETIAL_SUCCESS',
    FETCH_SALE_FAILURE: 'FETCH_SALE_FAILURE',
    SET_SALE_PURCHASE: 'SET_CURRENT_SALE',
    
}

export default SaleActionType;